### ISSUE TITLE
two connectione

### ISSUE THREAD

**Issue by thobui14ig** [Aliheym/typeorm-transactional#11]
how to use 2 service transaction, hellpe me, i am from VietNam
    await this.resourcesRepository.save(data);
    await this.userService.saveUser();

**Comment by artem-derevyanko** [comment]
Hello, can you give more information about what you want to do if possible?

Do you want to run your code in one transaction?

```javascript
await this.resourcesRepository.save(data);
await this.userService.saveUser();
```

**Comment by Aliheym** [comment]
Hello @thobui14ig , can you give more information about what you want to do if possible?

Do you want to run your code in one transaction?

```javascript
await this.resourcesRepository.save(data);
await this.userService.saveUser();
```

**Comment by thobui14ig** [comment]
>yes, i want one transaction, that is two difference service, if this.userService.saveUser() error i want rollback  this.resourcesRepository.save(data), help me

**Comment by thobui14ig** [comment]
> Hello @thobui14ig , can you give more information about what you want to do if possible?
> 
> Do you want to run your code in one transaction?
> 
> ```js
> await this.resourcesRepository.save(data);
> await this.userService.saveUser();
> ```

help me

**Comment by Aliheym** [comment]
Hi, @thobui14ig.

1. You need to connect this library (https://github.com/Aliheym/typeorm-transactional#initialization) and example for Nest.js (https://github.com/Aliheym/typeorm-transactional#usage)
2. You need to use `Transactional` decorator in the method that contains a code that you want to "wrap" in the one transactions. For example it can be a controller method:

```typescript
@Patch('/users/:id`)
@Transactional()
async updateUser(data) {
    await this.resourcesRepository.save(data);
    await this.userService.saveUser();
}
```

or it can be any other method:

```typescript
class UsersService {
@Transactional()
async updateUser(data) {
    await this.resourcesRepository.save(data);
    await this.userService.saveUser();
}
```

You can ask questions if you have troubles with something.

**Comment by Aliheym** [comment]
Feel free to reopen issue if you have issues.
