### ISSUE TITLE
 EventEmitter memory leak detected

### ISSUE THREAD

**Issue by herenickname** [Aliheym/typeorm-transactional#13]
I use a lot of runOnTransactionCommit hooks, so I caught this warning at runtime:
```
(node:25728) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 commit listeners added to [EventEmitter]. Use emitter.setMaxListeners() to increase limit
    at _addListener (node:events:587:17)
    at EventEmitter.addListener (node:events:605:10)
    at EventEmitter.added (/root/v3/node_modules/emitter-listener/listener.js:93:27)
    at EventEmitter.once (node:events:649:8)
    at runOnTransactionCommit (/root/v3/node_modules/typeorm-transactional/dist/hooks/index.js:103:48)
```
It would be nice if you open events' method `setMaxListeners` publicly available to manage.

Thanks for this fork and your work.

**Comment by Aliheym** [comment]
Hi, thanks for your issue.

I added options `maxHookHandlers`  to handle this issue in new version.

```typescript
  initializeTransactionalContext({ maxHookHandlers: 0 });
```

**Comment by herenickname** [comment]
> Hi, thanks for your issue.
> 
> I added options `maxHookHandlers` to handle this issue in new version.
> 
> ```ts
>   initializeTransactionalContext({ maxHookHandlers: 0 });
> ```

Seems its still not implemented :(
