### ISSUE TITLE
Should return `addTransactionalDataSource` as promise

### ISSUE THREAD

**Issue by sctouch** [Aliheym/typeorm-transactional#16]
The problem is when we are using it with Nestjs, and using `dataSourceFactory`, it will resolve the wrong return type. since the `dataSourceFactory` need to return as `Promise<DataSource>`

For a temporary solution I have to do like: 
```ts
dataSourceFactory: (options) => {
  if (!options) {
    throw new Error('Invalid options passed')
  }

  return addTransactionalDataSource(new DataSource(options)) as unknown as Promise<DataSource>
},
```

**Comment by neoatlan** [comment]
Please put `async` keyword to the arrow function

**Comment by chantouchsek** [comment]
But `async` alone is not working and I don't want to disable the eslint for that kind.

**Comment by neoatlan** [comment]
I think your project has a rule that forbids the async keyword on functions that only have synchronous operations.
How about this way?
```return Promise.resolve(addTransactionalDataSource(...))```

**Comment by sctouch** [comment]
Thanks, man it's working.
