### ISSUE TITLE
Not work if using custom repository

### ISSUE THREAD

**Issue by vvtri** [Aliheym/typeorm-transactional#19]
Hi, I am using a custom repository with NestJs like in this post https://stackoverflow.com/a/72887316/19150323, when I call save method, it auto commit. This is my config, thanks you for making this library
![image](https://user-images.githubusercontent.com/82482496/201452461-8a14d533-3627-4d2e-ad22-42a58da2ca3a.png)
![image](https://user-images.githubusercontent.com/82482496/201452469-040ac63a-0225-4f56-a7ab-7f890cd28a96.png)

**Comment by vvtri** [comment]
I made a wrong configuration.

**Comment by Aliheym** [comment]
Hi, thanks for your issue. This lib hasn't support custom repositories yet, but we have a PR for this feature. I will review and merge it as soon as possible.

**Comment by lukeurban** [comment]
I can confirm that Custom Repositories are left out ;)

**Comment by Aliheym** [comment]
Hi guys, I added some basic tests to check custom repositories and with #14 PR it works well for me. Maybe you can give me some examples to check?

**Comment by vvtri** [comment]
> Hi guys, I added some basic tests to check custom repositories and with #14 PR it works well for me. I don't see any issues. Maybe you can give me some examples to check?

I just made some basic test, maybe some mistakes were made. When this feature can be released ?

**Comment by Aliheym** [comment]
> > Hi guys, I added some basic tests to check custom repositories and with #14 PR it works well for me. I don't see any issues. Maybe you can give me some examples to check?
> 
> I just made some basic test, maybe some mistakes were made. When this feature can be released ?

In a few hours

**Comment by Aliheym** [comment]
New version with this feature was released.
