### ISSUE TITLE
Support for AsyncLocalStorage?

### ISSUE THREAD

**Issue by natoszme** [Aliheym/typeorm-transactional#22]
Hi there!

First of all, thanks for this implementation, seems really cool!
I'm about to start a project using Nest and this was the best library I found for transaction management. The only thing stopping me from using it is the fact that `cls-hooked` uses [async_hooks](https://github.com/nodejs/node/blob/main/doc/api/async_hooks.md) under the hood, which is considered unstable:

> Stability: 1 - Experimental. Please migrate away from this API, if you can. We do not recommend using the [createHook](https://github.com/nodejs/node/blob/main/doc/api/async_hooks.md#async_hookscreatehookcallbacks), [AsyncHook](https://github.com/nodejs/node/blob/main/doc/api/async_hooks.md#class-asynchook), and [executionAsyncResource](https://github.com/nodejs/node/blob/main/doc/api/async_hooks.md#async_hooksexecutionasyncresource) APIs as they have usability issues, safety risks, and performance implications. Async context tracking use cases are better served by the stable [AsyncLocalStorage](https://github.com/nodejs/node/blob/main/doc/api/async_context.md#class-asynclocalstorage) API.

Is there any plan to migrate from `cls-hooked` to native's [AsyncLocalStorage](https://nodejs.org/docs/latest-v16.x/api/async_context.html#class-asynclocalstorage)? I think it'd be an amazing stability improvement for this library.
In fact there is [this](https://github.com/LuanMaik/nestjs-typeorm-transaction-unitOfWork-AsyncLocalStorage) implementation for resolving quite the same problem (but without maintenance).

Thank you for your work!

**Comment by Aliheym** [comment]
Hi, I think that's a great idea. I've figured out `AsyncLocalStorage` more and I really like it. I think it would be a good idea to use it and drop the `cls-hooked` dependency. Thanks for this point.

The only thing I'm worried about is that now we'll have to stop to support some versions of Node.js.

**Comment by natoszme** [comment]
I know that it may not be so simple, but something similar to what [cls-hooked does](https://github.com/jeff-lewis/cls-hooked#when-running-nodejs-version--8-this-module-uses-asyncwrap-which-is-an-unsupported-nodejs-api-so-please-consider-the-risk-before-using-it) may be done (using `cls-hooked` for node < 16, `AsyncLocalStorage` for node >= 16)

**Comment by natoszme** [comment]
hi there! @Aliheym are there any plans to implement this one? thanks!

**Comment by Aliheym** [comment]
> hi there! @Aliheym are there any plans to implement this one? thanks!

Hi, yes. I am planning to start to implement it on this week. 🙂

**Comment by Aliheym** [comment]
> hi there! @Aliheym are there any plans to implement this one? thanks!

Hi, yes. I am planning to start to implement it on this week. 🙂

**Comment by ahmedkoshek** [comment]
Hi @Aliheym, any updates on supporting AsyncLocalStorage.
The only thing stopping me from using it is the fact that cls-hooked uses async_hooks under the hood, which is considered unstable.
